stages:
  test_visual_bert:
    cmd: >
        python hateful_memes/models/visual_bert.py
        --batch_size 4 
        --fast_dev_run True
        | tee logs/test_visual_bert.log 2>&1
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/models/visual_bert.py
    outs:
      - logs/test_visual_bert.log

  visual_bert:
    vars:
      - config/visual_bert.yaml
    cmd: >
        python hateful_memes/models/visual_bert.py
        --batch_size ${batch_size}
        --lr ${lr}
        --epochs ${epochs}
        --max_length ${max_length}
        --dense_dim ${dense_dim}
        --dropout_rate ${dropout_rate}
        --gradient_clip_value ${gradient_clip_value}
        --model_dir data/06_models/visual_bert
    deps:
      - logs/test_visual_bert.log
      - data/01_raw/hateful_memes
      - hateful_memes/models/visual_bert.py
    outs:
      - data/06_models/visual_bert

  test_simple_mlp_image:
    cmd: >
        python hateful_memes/models/simple_mlp_image.py 
        --fast_dev_run True
        > logs/test_simple_mlp_image.log 2>&1
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/models/simple_mlp_image.py
    outs:
      - logs/test_simple_mlp_image.log
        
  simple_mlp_image:
    vars:
      - config/simple_mlp_image.yaml
    cmd: >
        python hateful_memes/models/simple_mlp_image.py
        --batch_size ${batch_size}
        --lr ${lr}
        --epochs ${epochs}
        --dense_dim ${dense_dim}
        --dropout_rate ${dropout_rate}
        --grad_clip ${gradient_clip_value}
        --model_dir data/06_models/simple_mlp_image
    deps:
      - logs/test_simple_mlp_image.log
      - data/01_raw/hateful_memes
      - hateful_memes/models/simple_mlp_image.py
      - hateful_memes/models/baseline.py
    outs:
      - data/06_models/simple_mlp_image

  test_simple_image:
    cmd: >
        python hateful_memes/models/simple_image.py 
        --fast_dev_run True
        | tee logs/test_simple_image.log 2>&1
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/models/simple_image.py
    outs:
      - logs/test_simple_image.log

  simple_image:
    vars: 
      - config/simple_image.yaml
    cmd: >
        python hateful_memes/models/simple_image.py
        --batch_size ${batch_size}
        --lr ${lr}
        --epochs ${epochs}
        --dense_dim ${dense_dim}
        --dropout_rate ${dropout_rate}
        --grad_clip ${gradient_clip_value}
        --model_dir data/06_models/simple_image
        --batch_norm ${batch_norm}
    deps:
      - logs/test_simple_image.log
      - data/01_raw/hateful_memes
      - hateful_memes/models/simple_image.py
      - hateful_memes/models/baseline.py
    outs:
      - data/06_models/simple_image

  baseline:
    cmd: python hateful_memes/models/baseline_algorithm.py
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/models/baseline_algorithm.py

