stages:
  test_visual_bert:
    cmd: >
        python -m hateful_memes.models.visual_bert
        --batch_size 4 
        --fast_dev_run True
        --log_dir logs/test_simple_visual_bert_image_metrics
        --project test
        | tee logs/test_visual_bert.log 2>&1
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/models/visual_bert.py
    outs:
      - logs/test_visual_bert.log

  visual_bert:
    vars:
      - config/visual_bert.yaml
    cmd: >
        python -m hateful_memes.models.visual_bert
        --batch_size ${batch_size}
        --lr ${lr}
        --epochs ${epochs}
        --max_length ${max_length}
        --dense_dim ${dense_dim}
        --dropout_rate ${dropout_rate}
        --gradient_clip_value ${gradient_clip_value}
        --model_dir data/06_models/visual_bert
    deps:
      - logs/test_visual_bert.log
      - data/01_raw/hateful_memes
      - hateful_memes/models/visual_bert.py
    outs:
      - data/06_models/visual_bert
    # plots:
    #   - data/08_reporting/visual_bert/scalars
    # metrics:
    #   - data/08_reporting/visual_bert.json

  test_simple_mlp_image:
    cmd: >
        python -m hateful_memes.models.simple_mlp_image
        --fast_dev_run True
        --log_dir logs/test_simple_mlp_image_metrics
        --project test
        | tee logs/test_simple_mlp_image.log 2>&1
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/models/simple_mlp_image.py
    outs:
      - logs/test_simple_mlp_image.log
        
  simple_mlp_image:
    vars:
      - config/simple_mlp_image.yaml
    cmd: >
        python -m hateful_memes.models.simple_mlp_image
        --batch_size ${batch_size}
        --lr ${lr}
        --epochs ${epochs}
        --dense_dim ${dense_dim}
        --dropout_rate ${dropout_rate}
        --grad_clip ${gradient_clip_value}
        --model_dir data/06_models/simple_mlp_image
    deps:
      - logs/test_simple_mlp_image.log
      - data/01_raw/hateful_memes
      - hateful_memes/models/simple_mlp_image.py
      - hateful_memes/models/baseline.py
    outs:
      - data/06_models/simple_mlp_image
    # plots:
    #   - data/08_reporting/simple_mlp_image/scalars
    # metrics:
    #   - data/08_reporting/simple_mlp_image.json

  test_simple_image:
    cmd: >
        python -m hateful_memes.models.simple_image
        --log_dir logs/test_simple_image_metrics
        --project test
        --fast_dev_run True
        | tee logs/test_simple_image.log 2>&1
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/models/simple_image.py
    outs:
      - logs/test_simple_image.log

  simple_image:
    vars: 
      - config/simple_image.yaml
    cmd: >
        python -m hateful_memes.models.simple_image
        --batch_size ${batch_size}
        --lr ${lr}
        --epochs ${epochs}
        --dense_dim ${dense_dim}
        --dropout_rate ${dropout_rate}
        --grad_clip ${gradient_clip_value}
        --model_dir data/06_models/simple_image
        --batch_norm ${batch_norm}
    deps:
      - logs/test_simple_image.log
      - data/01_raw/hateful_memes
      - hateful_memes/models/simple_image.py
      - hateful_memes/models/baseline.py
    outs:
      - data/06_models/simple_image
    # plots:
    #   - data/08_reporting/simple_image/scalars
    # metrics:
    #   - data/08_reporting/simple_image.json

  baseline:
    cmd: python -m hateful_memes.models.baseline_algorithm
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/models/baseline_algorithm.py

  test_simple_text:
    cmd: >
        python -m hateful_memes.models.simple_text
        --fast_dev_run True
        | tee logs/test_simple_text.log 2>&1
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/models/simple_text.py
    outs:
      - logs/test_simple_text.log

  simple_text:
    vars: 
      - config/simple_text.yaml
    cmd: >
        python -m hateful_memes.models.simple_text
        --batch_size ${batch_size}
        --lr ${lr}
        --embed_dim ${embed_dim}
        --dense_dim ${dense_dim}
        --max_length ${max_length}
        --tokenizer_name ${tokenizer_name}
        --grad_clip ${grad_clip}
        --dropout_rate ${dropout_rate}
        --epochs ${epochs}
        --model_dir data/06_models/simple_text
    deps:
      - data/01_raw/hateful_memes
      - logs/test_simple_image.log
      - hateful_memes/models/simple_text.py
    outs:
      - data/06_models/simple_text
