stages:
  visual_bert:
    vars:
      - config/visual_bert.yaml
    cmd: >
        python src/models/visual_bert.py
        --batch_size ${batch_size}
        --lr ${lr}
        --epochs ${epochs}
        --max_length ${max_length}
        --dense_dim ${dense_dim}
        --dropout_rate ${dropout_rate}
        --gradient_clip_value ${gradient_clip_value}
        --model_dir data/06_models/visual_bert
    deps:
      - data/01_raw/hateful_memes
      - src/models/visual_bert.py
    outs:
      - data/06_models/visual_bert
    live:
        data/08_reporting/visual_bert:
          summary: true
          html: true

  simple_mlp_image:
    vars:
      - config/simple_mlp_image.yaml
    cmd: >
        python src/models/simple_mlp_image.py
        --batch_size ${batch_size}
        --lr ${lr}
        --epochs ${epochs}
        --dense_dim ${dense_dim}
        --dropout_rate ${dropout_rate}
        --grad_clip ${gradient_clip_value}
        --model_dir data/06_models/simple_mlp_image
    deps:
      - data/01_raw/hateful_memes
      - src/models/simple_mlp_image.py
    outs:
      - data/06_models/simple_mlp_image
    live:
        data/08_reporting/simple_mlp_image:
          summary: true
          html: true   

  simple_image:
    vars: 
      - config/simple_image.yaml
    cmd: >
        python src/models/simple_image.py
        --batch_size ${batch_size}
        --lr ${lr}
        --epochs ${epochs}
        --dense_dim ${dense_dim}
        --dropout_rate ${dropout_rate}
        --grad_clip ${gradient_clip_value}
        --model_dir data/06_models/simple_image
        --batch_norm ${batch_norm}
    deps:
      - data/01_raw/hateful_memes
      - src/models/simple_image.py
    outs:
      - data/06_models/simple_image
    live:
        data/08_reporting/simple_image:
          summary: true
          html: true

  baseline_model:
    cmd: python src/models/baseline_algorithm.py
    deps:
      - data/01_raw/hateful_memes
      - src/models/baseline_algorithm.py
    live:
        data/08_reporting/baseline:
          summary: true
          html: false

