stages:
  test_visual_bert_with_od:
    cmd: >
        python -m hateful_memes.models.visual_bert_with_od
        --batch_size 4 
        --fast_dev_run True
        && echo "PASSED" > logs/test_visual_bert_with_od.log
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/models/visual_bert_with_od.py
    outs:
      - logs/test_visual_bert_with_od.log

  visual_bert_with_od:
    vars:
      - config/visual_bert_with_od.yaml
    cmd: >
        python -m hateful_memes.models.visual_bert_with_od
        --lr ${lr}
        --epochs ${epochs}
        --max_length ${max_length}
        --dense_dim ${dense_dim}
        --dropout_rate ${dropout_rate}
        --num_queries ${num_queries}
        --batch_size ${batch_size}
        --grad_clip ${gradient_clip_value}
        --model_dir data/06_models/visual_bert_with_od
    deps:
      - logs/test_visual_bert_with_od.log
      - data/01_raw/hateful_memes
      - hateful_memes/data/hateful_memes.py
      - hateful_memes/models/base.py
      - hateful_memes/models/visual_bert_with_od.py
    outs:
      - data/06_models/visual_bert_with_od

  test_beit:
    cmd: >
        python -m hateful_memes.models.baseIT
        --model_name vit
        --batch_size 4 
        --fast_dev_run True
        && echo "PASSED" > logs/test_beit.log
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/data/hateful_memes.py
      - hateful_memes/models/baseIT.py
    outs:
      - logs/test_beit.log

  beit:
    vars:
      - config/beit.yaml
    cmd: >
        python -m hateful_memes.models.baseIT
        --model_name ${model_name}
        --batch_size ${batch_size}
        --lr ${lr}
        --epochs ${epochs}
        --max_length ${max_length}
        --dense_dim ${dense_dim}
        --dropout_rate ${dropout_rate}
        --grad_clip ${gradient_clip_value}
        --model_dir data/06_models/beit
        --project beit
    deps:
      - logs/test_beit.log
      - data/01_raw/hateful_memes
      - hateful_memes/data/hateful_memes.py
      - hateful_memes/models/baseIT.py
    outs:
      - data/06_models/beit

  test_vit:
    cmd: >
        python -m hateful_memes.models.baseIT
        --model_name vit
        --batch_size 4 
        --fast_dev_run True
        --log_dir logs/test_simple_vit_image_metrics
        --project test
        && echo "PASSED" > logs/test_vit.log
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/data/hateful_memes.py
      - hateful_memes/models/baseIT.py
    outs:
      - logs/test_vit.log

  vit:
    vars:
      - config/vit.yaml
    cmd: >
        python -m hateful_memes.models.baseIT
        --model_name ${model_name}
        --batch_size ${batch_size}
        --lr ${lr}
        --epochs ${epochs}
        --max_length ${max_length}
        --dense_dim ${dense_dim}
        --dropout_rate ${dropout_rate}
        --grad_clip ${grad_clip}
        --model_dir data/06_models/vit
        --project vit
    deps:
      - logs/test_vit.log
      - data/01_raw/hateful_memes
      - hateful_memes/data/hateful_memes.py
      - hateful_memes/models/baseIT.py
    outs:
      - data/06_models/vit

  test_visual_bert:
    cmd: >
        python -m hateful_memes.models.visual_bert
        --batch_size 4 
        --fast_dev_run True
        --log_dir logs/test_simple_visual_bert_image_metrics
        --project test
        && echo "PASSED" > logs/test_visual_bert.log 
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/data/hateful_memes.py
      - hateful_memes/models/base.py
      - hateful_memes/models/visual_bert.py
    outs:
      - logs/test_visual_bert.log

  visual_bert:
    vars:
      - config/visual_bert.yaml
    cmd: >
        python -m hateful_memes.models.visual_bert
        --batch_size ${batch_size}
        --lr ${lr}
        --epochs ${epochs}
        --max_length ${max_length}
        --dense_dim ${dense_dim}
        --dropout_rate ${dropout_rate}
        --grad_clip ${gradient_clip_value}
        --model_dir data/06_models/visual_bert
        --freeze ${freeze}
    deps:
      - logs/test_visual_bert.log
      - data/01_raw/hateful_memes
      - hateful_memes/data/hateful_memes.py
      - hateful_memes/models/base.py
      - hateful_memes/models/visual_bert.py
    outs:
      - data/06_models/visual_bert

  test_electra:
    vars:
      - config/electra.yaml
    cmd: >
        python -m hateful_memes.models.auto_text_model
        --batch_size 4 
        --fast_dev_run True
        --model_name ${model_name}
        && echo "PASSED" > logs/test_electra.log 
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/data/hateful_memes.py
      - hateful_memes/models/auto_text_model.py
    outs:
      - logs/test_electra.log

  electra:
    vars:
      - config/electra.yaml
    cmd: >
        python -m hateful_memes.models.auto_text_model
        --batch_size ${batch_size}
        --lr ${lr}
        --epochs ${epochs}
        --max_length ${max_length}
        --dense_dim ${dense_dim}
        --dropout_rate ${dropout_rate}
        --grad_clip ${gradient_clip_value}
        --model_name ${model_name}
        --project electra
        --model_dir data/06_models/electra
    deps:
      - logs/test_electra.log
      - data/01_raw/hateful_memes
      - hateful_memes/data/hateful_memes.py
      - hateful_memes/models/auto_text_model.py
    outs:
      - data/06_models/electra

  test_distilbert:
    vars:
      - config/distilbert.yaml
    cmd: >
        python -m hateful_memes.models.auto_text_model
        --batch_size 4 
        --fast_dev_run True
        --model_name ${model_name}
        && echo "PASSED" > logs/test_distilbert.log 
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/data/hateful_memes.py
      - hateful_memes/models/auto_text_model.py
    outs:
      - logs/test_distilbert.log

  distilbert:
    vars:
      - config/distilbert.yaml
    cmd: >
        python -m hateful_memes.models.auto_text_model
        --batch_size ${batch_size}
        --lr ${lr}
        --epochs ${epochs}
        --max_length ${max_length}
        --dense_dim ${dense_dim}
        --dropout_rate ${dropout_rate}
        --grad_clip ${gradient_clip_value}
        --model_name ${model_name}
        --project distilbert
        --model_dir data/06_models/distilbert
    deps:
      - logs/test_distilbert.log
      - data/01_raw/hateful_memes
      - hateful_memes/data/hateful_memes.py
      - hateful_memes/models/auto_text_model.py
    outs:
      - data/06_models/distilbert

  test_simple_mlp_image:
    cmd: >
        python -m hateful_memes.models.simple_mlp_image
        --fast_dev_run True
        --log_dir logs/test_simple_mlp_image_metrics
        --project test
        && echo "PASSED" > logs/test_simple_mlp_image.log 
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/data/hateful_memes.py
      - hateful_memes/models/base.py
      - hateful_memes/models/simple_mlp_image.py
    outs:
      - logs/test_simple_mlp_image.log
        
  simple_mlp_image:
    vars:
      - config/simple_mlp_image.yaml
    cmd: >
        python -m hateful_memes.models.simple_mlp_image
        --batch_size ${batch_size}
        --lr ${lr}
        --epochs ${epochs}
        --dense_dim ${dense_dim}
        --dropout_rate ${dropout_rate}
        --grad_clip ${gradient_clip_value}
        --model_dir data/06_models/simple_mlp_image
    deps:
      - logs/test_simple_mlp_image.log
      - data/01_raw/hateful_memes
      - hateful_memes/data/hateful_memes.py
      - hateful_memes/models/base.py
      - hateful_memes/models/simple_mlp_image.py
    outs:
      - data/06_models/simple_mlp_image

  test_simple_image:
    cmd: >
        python -m hateful_memes.models.simple_image
        --log_dir logs/test_simple_image_metrics
        --project test
        --fast_dev_run True
        && echo "PASSED" > logs/test_simple_image.log
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/data/hateful_memes.py
      - hateful_memes/models/base.py
      - hateful_memes/models/simple_image.py
    outs:
      - logs/test_simple_image.log

  simple_image:
    vars: 
      - config/simple_image.yaml
    cmd: >
        python -m hateful_memes.models.simple_image
        --batch_size ${batch_size}
        --lr ${lr}
        --epochs ${epochs}
        --dense_dim ${dense_dim}
        --dropout_rate ${dropout_rate}
        --grad_clip ${gradient_clip_value}
        --model_dir data/06_models/simple_image
        --batch_norm ${batch_norm}
    deps:
      - logs/test_simple_image.log
      - data/01_raw/hateful_memes
      - hateful_memes/data/hateful_memes.py
      - hateful_memes/models/simple_image.py
      - hateful_memes/models/base.py
    outs:
      - data/06_models/simple_image

  baseline:
    cmd: python -m hateful_memes.models.baseline_algorithm
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/data/hateful_memes.py
      - hateful_memes/models/baseline_algorithm.py

  test_simple_text:
    cmd: >
        python -m hateful_memes.models.simple_text
        --fast_dev_run True
        && echo "PASSED" > logs/test_simple_text.log
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/data/hateful_memes.py
      - hateful_memes/models/base.py
      - hateful_memes/models/simple_text.py
    outs:
      - logs/test_simple_text.log

  simple_text:
    vars: 
      - config/simple_text.yaml
    cmd: >
        python -m hateful_memes.models.simple_text
        --batch_size ${batch_size}
        --lr ${lr}
        --num_layers ${num_layers}
        --embed_dim ${embed_dim}
        --dense_dim ${dense_dim}
        --max_length ${max_length}
        --tokenizer_name ${tokenizer_name}
        --grad_clip ${grad_clip}
        --dropout_rate ${dropout_rate}
        --epochs ${epochs}
        --model_dir data/06_models/simple_text
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/data/hateful_memes.py
      - logs/test_simple_text.log
      - hateful_memes/models/base.py
      - hateful_memes/models/simple_text.py
    outs:
      - data/06_models/simple_text

  test_super_model:
    cmd: >
        python -m hateful_memes.models.super_model
        --simple_image_ckpt data/06_models/simple_image
        --simple_text_ckpt data/06_models/simple_text
        --fast_dev_run True
        && echo "PASSED" > logs/test_super_model.log
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/data/hateful_memes.py
      - hateful_memes/models/base.py
      - hateful_memes/models/super_model.py
      - data/06_models/simple_image
      - data/06_models/simple_text
    outs:
      - logs/test_super_model.log

  super_model:
    vars: 
      - config/super_model.yaml
    cmd: >
        python -m hateful_memes.models.super_model
        --simple_image_ckpt data/06_models/simple_image
        --simple_mlp_image_ckpt data/06_models/simple_mlp_image
        --simple_text_ckpt data/06_models/simple_text
        --visual_bert_ckpt data/06_models/visual_bert
        --vit_ckpt data/06_models/vit
        --beit_ckpt data/06_models/beit
        --electra_ckpt data/06_models/electra
        --distilbert_ckpt data/06_models/distilbert
        --batch_size ${batch_size}
        --lr ${lr}
        --num_dense_layers ${num_dense_layers}
        --dense_dim ${dense_dim}
        --dropout_rate ${dropout_rate}
        --grad_clip ${grad_clip}
        --epochs ${epochs}
        --model_dir data/06_models/super_model
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/data/hateful_memes.py
      - logs/test_super_model.log
      - hateful_memes/models/base.py
      - hateful_memes/models/super_model.py
      - data/06_models/simple_image
      - data/06_models/simple_mlp_image
      - data/06_models/simple_text
      - data/06_models/visual_bert
      - data/06_models/vit
      - data/06_models/beit
      - data/06_models/electra
      - data/06_models/distilbert
        # --visual_bert_with_od_ckpt data/06_models/visual_bert_with_od
      # - data/06_models/visual_bert_with_od
    outs:
      - data/06_models/super_model