stages:
  test_visual_bert:
    cmd: >
        python -m hateful_memes.models.visual_bert
        --batch_size 4 
        --fast_dev_run True
        | tee logs/test_visual_bert.log 2>&1
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/models/visual_bert.py
    outs:
      - logs/test_visual_bert.log

  visual_bert:
    vars:
      - config/visual_bert.yaml
    cmd: >
        python -m hateful_memes.models.visual_bert
        --batch_size ${batch_size}
        --lr ${lr}
        --epochs ${epochs}
        --max_length ${max_length}
        --dense_dim ${dense_dim}
        --dropout_rate ${dropout_rate}
        --gradient_clip_value ${gradient_clip_value}
        --model_dir data/06_models/visual_bert
    deps:
      - logs/test_visual_bert.log
      - data/01_raw/hateful_memes
      - hateful_memes/models/visual_bert.py
    outs:
      - data/06_models/visual_bert

  test_electra:
    vars:
      - config/electra.yaml
    cmd: >
        python -m hateful_memes.models.auto_text_model
        --batch_size 4 
        --fast_dev_run True
        --model_name ${model_name}
        --model_name_simple ${model_name_simple}
        | tee logs/test_electra.log 2>&1
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/models/auto_text_model.py
    outs:
      - logs/test_electra.log

  electra:
    vars:
      - config/electra.yaml
    cmd: >
        python -m hateful_memes.models.auto_text_model
        --batch_size ${batch_size}
        --lr ${lr}
        --epochs ${epochs}
        --max_length ${max_length}
        --dense_dim ${dense_dim}
        --dropout_rate ${dropout_rate}
        --gradient_clip_value ${gradient_clip_value}
        --model_name ${model_name}
        --model_name_simple ${model_name_simple}
        --model_dir data/06_models/electra
    deps:
      - logs/test_electra.log
      - data/01_raw/hateful_memes
      - hateful_memes/models/auto_text_model.py
    outs:
      - data/06_models/electra

  test_distilbert:
    vars:
      - config/distilbert.yaml
    cmd: >
        python -m hateful_memes.models.auto_text_model
        --batch_size 4 
        --fast_dev_run True
        --model_name ${model_name}
        --model_name_simple ${model_name_simple}
        | tee logs/test_distilbert.log 2>&1
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/models/auto_text_model.py
    outs:
      - logs/test_distilbert.log

  distilbert:
    vars:
      - config/distilbert.yaml
    cmd: >
        python -m hateful_memes.models.auto_text_model
        --batch_size ${batch_size}
        --lr ${lr}
        --epochs ${epochs}
        --max_length ${max_length}
        --dense_dim ${dense_dim}
        --dropout_rate ${dropout_rate}
        --gradient_clip_value ${gradient_clip_value}
        --model_name ${model_name}
        --model_name_simple ${model_name_simple}
        --model_dir data/06_models/distilbert
    deps:
      - logs/test_distilbert.log
      - data/01_raw/hateful_memes
      - hateful_memes/models/auto_text_model.py
    outs:
      - data/06_models/distilbert

  test_simple_mlp_image:
    cmd: >
        python -m hateful_memes.models.simple_mlp_image
        --fast_dev_run True
        > logs/test_simple_mlp_image.log 2>&1
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/models/simple_mlp_image.py
    outs:
      - logs/test_simple_mlp_image.log
        
  simple_mlp_image:
    vars:
      - config/simple_mlp_image.yaml
    cmd: >
        python -m hateful_memes.models.simple_mlp_image
        --batch_size ${batch_size}
        --lr ${lr}
        --epochs ${epochs}
        --dense_dim ${dense_dim}
        --dropout_rate ${dropout_rate}
        --grad_clip ${gradient_clip_value}
        --model_dir data/06_models/simple_mlp_image
    deps:
      - logs/test_simple_mlp_image.log
      - data/01_raw/hateful_memes
      - hateful_memes/models/simple_mlp_image.py
      - hateful_memes/models/baseline.py
    outs:
      - data/06_models/simple_mlp_image

  test_simple_image:
    cmd: >
        python -m hateful_memes.models.simple_image
        --fast_dev_run True
        | tee logs/test_simple_image.log 2>&1
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/models/simple_image.py
    outs:
      - logs/test_simple_image.log

  simple_image:
    vars: 
      - config/simple_image.yaml
    cmd: >
        python -m hateful_memes.models.simple_image
        --batch_size ${batch_size}
        --lr ${lr}
        --epochs ${epochs}
        --dense_dim ${dense_dim}
        --dropout_rate ${dropout_rate}
        --grad_clip ${gradient_clip_value}
        --model_dir data/06_models/simple_image
        --batch_norm ${batch_norm}
    deps:
      - logs/test_simple_image.log
      - data/01_raw/hateful_memes
      - hateful_memes/models/simple_image.py
      - hateful_memes/models/baseline.py
    outs:
      - data/06_models/simple_image

  baseline:
    cmd: python -m hateful_memes.models.baseline_algorithm
    deps:
      - data/01_raw/hateful_memes
      - hateful_memes/models/baseline_algorithm.py

