visual_bert:
  batch_size: 16
  source: src/models/visual_bert.py
  lr: 1e-5
  epochs: 50
  max_length: 512
  dense_dim: 256
  dropout_rate: 0.1
  gradient_clip_value: 1.0

simple_mlp_image:
  batch_size: 64
  lr: 1e-5
  epochs: 50
  dense_dim: 128
  dropout_rate: 0.1
  gradient_clip_value: 1.0

simple_image:
  batch_size: 64
  lr: 1e-5
  epochs: 50
  dense_dim: 128
  dropout_rate: 0.1
  gradient_clip_value: 1.0
  batch_norm: true
