command:
  - ${env}
  - ${interpreter}
  - -m
  - hateful_memes.models.simple_image
  - ${args}
project: simple-image
method: random
metric:
  goal: minimize
  name: val/loss
parameters:
  dense_dim:
    values: [32, 64, 128, 256, 512, 1024, 2048]
  batch_size:
    values: [16, 32, 64, 128]
  lr:
    values: [0.1, 0.05, 0.01, 0.005, 0.001, 0.0005, 0.0001, 0.00001, 0.000001, 0.0000001]
  dropout_rate:
    values: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
  grad_clip:
    values: [0.1, 0.5, 1.0, 2.0, 5.0, 10.0]
  epochs:
    value: 100
# early_terminate:
#   type: hyperband
#   s: 2
#   eta: 3
#   max_iter: 27