command:
  - ${env}
  - ${interpreter}
  - -m
  - hateful_memes.models.simple_image
  - ${args}
project: simple-image
method: random
metric:
  goal: minimize
  name: val/acc
parameters:
  dense_dim:
    values: [32, 64, 128, 256, 512, 1024, 2048]
  batch_size:
    values: [4, 8, 16, 32, 64, 128, 256]
  lr:
    min: 0.0000001
    max: 0.1
  dropout_rate:
    min: 0.3
    max: 0.5
  grad_clip:
    min: 0.0
    max: 1.0
  epochs:
    value: 27
early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 27