name: Train all models
on: 
    workflow_dispatch:
    push:
      paths:
        - '**.js'
        - '**.py'
        - 'config/*yaml'
        - 'dvc.yaml'
        - .github/workflows/train.yml
# defaults:
#     run:
#       shell: bash
jobs:
  train:
    runs-on: [self-hosted, gpu]
    container:
      # image: etheredgeb/hateful-memes:cicd
      image: docker://iterativeai/cml:0-dvc2-base1-gpu
      # image: docker://python:3.8
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_AWS_SECRET_ACCESS_KEY }}
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        ENABLE_PROGRESS_BAR: 0
        TOKENIZERS_PARALLELISM: false
      options: --gpus all --shm-size=8G

    timeout-minutes: 1440  # Increased job runtime since ML is slow
    steps:
      # HOTFIX: https://github.com/actions/checkout/issues/760
      - name: work around permission issue
        run: git config --global --add safe.directory /__w/hateful_memes/hateful_memes
      - uses: actions/checkout@v2

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: Install requirements
        run: |
          pip install -r requirements.txt --no-cache-dir
          pip install -e .
          python -c 'import torch; from torch.utils.cpp_extension import CUDA_HOME; print(torch.cuda.is_available(), CUDA_HOME)'
          python -m pip install 'git+https://github.com/facebookresearch/detectron2.git@v0.5'

      - name: Pull data
        run: dvc pull data/01_raw/hateful_memes

      - name: Pull everything else
        continue-on-error: true
        run: dvc pull -a --run-cache


      - name: Train VisualBERT
        continue-on-error: true
        run: |
          dvc repro visual_bert
          dvc push --run-cache -d visual_bert

<<<<<<< HEAD
      - name: Train OFA
        continue-on-error: true
        run: |
          dvc repro train_hateful_ofa
          dvc push -d train_hateful_ofa

      # - name: Train Super Model
      #   continue-on-error: true
      #   run: |
      #     dvc repro super_model
      #     dvc push --run-cache -d super_model
=======
      - name: Train Super Model
        continue-on-error: true
        run: |
          dvc repro super_model
          dvc push --run-cache -d super_model
>>>>>>> 3dfd7b7 (Reverting changes to train.yml.)

      - name: Commit run
        run: |
          cml ci
          cml pr .
        
