name: Train all models
on: [push]
jobs:
  train:
    runs-on: [self-hosted, gpu]
    container:
      # image: etheredgeb/hateful-memes:cicd
      image: docker://iterativeai/cml:1-dvc2-base1-gpu
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_AWS_SECRET_ACCESS_KEY }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      options: --gpus all --shm-size=2G
    timeout-minutes: 1440  # Increased job runtime since ML is slow
    steps:
      - uses: actions/checkout@v2
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - run: |
          pip install -r requirements.txt
          pip install -e .

      - name: Pull data
        run: dvc pull data/01_raw/hateful_memes

      - name: Train VisualBERT
        continue-on-error: true
        run: |
          dvc repro visual_bert
          cml ci

      - name: Train Simple Image Model
        continue-on-error: true
        run: |
          dvc repro simple_image_model
          cml ci
